services:
  postgres:
    image: kartoza/postgis:18-3.6
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS}
        - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m

  waterbodies:
    build:
      context: .
      args:
        - BUILD_ENV=prod
    environment:
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - ODC_DEFAULT_INDEX_DRIVER=postgres
      - ODC_DEFAULT_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_DB}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_NO_SIGN_REQUEST=${AWS_NO_SIGN_REQUEST}
      - AWS_SESSION_TOKEN
    volumes:
      - .:/code
    depends_on:
        postgres:
          condition: service_healthy
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 180 ; done"]
