name: waterbodies-env
channels:
  - conda-forge
dependencies:
  # base
  - python==3.12.3
  - gdal==3.12.2
  - libgdal
  - libgdal-arrow-parquet
  - pip-tools
  # for psycopg2 and python-geohash
  - compilers
  # for spatialite
  - libspatialite
  # developer tools
  - curl
  - unzip
  - jq
  