[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "waterbodies"
version = "0.1.28"
authors = [{name = "Digital Earth Africa", email = "systems@digitalearthafrica.org"}]
maintainers = [{name = "Digital Earth Africa", email = "systems@digitalearthafrica.org"}]
description = "DE Africa waterbodies"
readme =  {file = "README.md", content-type = "text/markdown"}
license = "Apache-2.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
requires-python = ">=3.10"
dependencies = [
    "click",
    "datacube[s3, distributed, performance]>=1.9.0",
    "fsspec",
    "geoalchemy2",
    "geopandas[all]",
    "numpy",
    "odc-dscache",
    "odc-geo",
    "odc-stats>=1.9.6",
    "pandas",
    "python-dotenv",
    "python-geohash",
    "rasterio",
    "rioxarray",
    "s3fs",
    "scikit-image",
    "sqlalchemy",
    "alembic",
    "toolz",
    "tqdm",
    "xarray[complete]",
]

[project.optional-dependencies]
tests = [
    "pytest",
    "coverage",
    "odc-apps-dc-tools>1.9.7",
]
lint = [
    "black[jupyter]",
    "flake8",
    "mypy",
    "isort>=5.0.0",
    "pre-commit",
]
viz = ["lxml"]
dev = ["waterbodies[tests, lint, viz]"]

[project.urls]
Repository = "https://github.com/digitalearthafrica/waterbodies.git"
"Bug Tracker" = "https://github.com/digitalearthafrica/waterbodies/issues"

[project.scripts]
waterbodies = "waterbodies.cli.main:waterbodies"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.isort]
profile = "black"

[tool.black]
line-length = 100

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"