name: Publish Docker Image

on:
  workflow_run:
    workflows:
      - "Create a new tag"
    types: 
      - completed
  workflow_dispatch:


env:
  IMAGE_NAME: victorianeema/waterbodies

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Get version number for tagging the image
        run: |
          git fetch --all --tags
          pip install setuptools-scm
          echo "VERSION=$(python -m setuptools_scm  | sed s/+/./g)" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.VERSION }}
